### ISSUE TITLE
minetest.override_chatcommand doesn't work

### ISSUE THREAD

**Issue by luk3yx** [appgurueu/cmdlib#3]
Nothing seems to happen if you try and override chatcommands with `minetest.override_chatcommand`. If I run the below code and do `/msg test hello`, I still get a "The player test is not online" message.

```lua
minetest.override_chatcommand("msg", {
    func=function() return true, 'Test' end
})
```

Additionally, if you don't provide `func` to `minetest.override_chatcommand` it errors:

```lua
minetest.override_chatcommand("msg", {
    description = "Testing"
})
```

**Comment by appgurueu** [comment]
Fixed in https://github.com/appgurueu/cmdlib/commit/17cbcb62b364abac0b007656d5f84228507a18bc
